name: _Reusable publish template

on:
  workflow_call:
    inputs:
      affected-plugin:
        type: string
        description: Nx plugins affected by the changes
        required: true
      version-tag:
        type: string
        description: Whether to publish a beta version or latest
        required: false
    secrets:
      NODE_AUTH_TOKEN:
        description: NPM token
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
        working-directory: plugins/${{ inputs.affected-plugin }}

      - name: Publish version dry-run
        run: npm publish --access public --tag ${{ inputs.version-tag && 'beta' || 'latest' }} --dry-run
        working-directory: plugins/${{ inputs.affected-plugin }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      # if the branch is the default branch, the latest tag is applied
      - name: Publish package on NPM [latest] 📦
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push'
        run: npm publish --access public
        working-directory: plugins/${{ inputs.affected-plugin }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      # if the branch is not the default branch, the beta tag is applied
      - name: Publish package on NPM [beta] 📦
        if: github.event_name == 'pull_request'
        run: |
          VERSION=$(cat package-lock.json | jq -r '.version')
          SHORT_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)
          npm version $VERSION-beta.pr-${{ github.event.number }}.$SHORT_SHA
          npm publish --access public --tag beta
        working-directory: plugins/${{ inputs.affected-plugin }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
